### ISSUE TITLE
Add ability to save and recall personal annotations

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/mirador_sul#5]

**Comment by aeschylus** [comment]
In the technical planning meeting today, we uncovered some complications with respect to the public/private behaviour of annotations.

In the project planning meeting, we had decided to have all annotations created in any workspace or collection recalled by any workspace that references the relevant canvas (using Mirador's default behaviour of just querying on page turn for any matching annotations). However, we wanted the annotations to be scoped to the user.

What do we want the behaviour to be for workspaces that are being viewed by someone other than the user who created the annotations? Since the viewing user is not logged in as the creator, should they not see any annotations? If they are able to see annotations, how should we restrict their ability to edit those annotations and realise that technically?

**Comment by blalbrit** [comment]
I think this is out of scope for the MVP for May. We should do a full requirements pass post-May for the annotation creation & publication workflow.
