### ISSUE TITLE
CSS is beefing up font sizes and Mirador does not override them.

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/mirador_sul#60]
See the table of contents.

**Comment by mejackreed** [comment]
Should mirador have an opinion on the consuming application's font-sizes? Or should this be namespaced somehow in Mirador?

**Comment by csbailey5t** [comment]
Most of the Mirador css is actually namespaced to `.mirador-container` since the refactor using less. Unfortunately there are namespaced rules for the sidepanel headers for font-weight, but not font-size. 

This probably should be a rule added to the namespaced sidepanel styling, which could then be overridden by a consuming application.

**Comment by aeschylus** [comment]
For now we can add some css to the Mirador container, but this clearly slipped through the cracks with Mirador testing/LESS refactor.
