### ISSUE TITLE
[production] ActiveRecord::InvalidForeignKey on collection deletion

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/mirador_sul#69]
When deleting a collection, we get a 500 server error. We may need to use the `has_many ... dependent: ...` call in the collections model.

See below

[mirador_sul/production] ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "collections" violates foreign key constraint "fk_rails_0f16b7366a" on table "workspaces"DETAIL:  Key (id)=(1) is still referenced from table "workspaces".: DELETE FROM "collections" WHERE "collections"."id" = $1

## Backtrace

    line 49 of [PROJECT_ROOT]/app/controllers/collections_controller.rb: destroy

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51654/faults/33222324)

**Comment by jkeck** [comment]
Setting `dependent: :destroy` would destroy all the workspaces, which I would not be  desired.

I believe we can set `dependent: :nullify`, however the sqlite3 adapter does not support foreign key so I can't write a meaningful test.

Another option would be to remove the `foreign_key` constraint in the database itself (though a migration) since we know that we want to retain workspaces regardless of whether the original collection exists or not.

**Comment by drh-stanford** [comment]
Yeah the original data model had workspaces fully within collections -- they couldn't exist outside them. But sounds like we want to keep around workspaces. So, I agree that we need to modify the data model so that `workspaces.collection_id` can be null.
