### ISSUE TITLE
Figure out server environment for mirador@stanford

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/mirador_sul#8]
- [x] where should this live long term
 - [x] spin up VMs for Mirador and SAS
   - [x] stage
   - [x] prod

**Comment by blalbrit** [comment]
Decision is to house Mirador at Stanford locally instead of AWS for a number of reasons (though we aren't going to take down the current AWS boxes).  Environment will be:

sul-mirador-prod.stanford.edu (hosting Mirador & simpleAnnotationServer)
sul-mirador-stage.stanford.edu (hosting Mirador & simpleAnnotationServer)
sul-mirador-demo.stanford.edu (hosting Mirador only - this could just be the AWS box that currently has mirador.stanford.edu - would be reserved either for special demos or feature demos - no annotation store other than localhost)

Of these - prod is built but needs some puppet-y things to be usable, -demo is on AWS, and Erin has a ticket filed for -stage: https://github.com/sul-dlss/operations-tasks/issues/270

**Comment by drh-stanford** [comment]
note that depending on the other services we may need to implement for mirador at stanford, it may complicate the configuration of these VMs -- for example, java (SAS), httpd/node.js(?) (Mirador) and rails/mysql (TBD services) configuration. i dunno what devops' position is on such a configuration and whether a docker build may be in order. anyway, i'm fuzzy on this issue but i thought i'd highlight this aspect.

cc @eefahy

**Comment by drh-stanford** [comment]
we decided on `sul-mirador-{stage,prod}` and `sul-mirador-sas-{stage,prod}`.

**Comment by drh-stanford** [comment]
this is finished.
